---
blank_issues_enabled: false
contact_links:
  - name: Use your data injecting your model with ObservableObject and ObservedObject Community Support
    url: https://github.com/developer-academy-unina/Tutorial-Use-your-data-injecting-your-model-with-ObservableObject-and-ObservedObject/discussions
    about: Please ask and answer questions here.
